### ISSUE TITLE
email templateId

### ISSUE THREAD

**Issue by mulyoved** [decileapp/decile#1]
[Hard coded](https://github.com/decileapp/decile/blob/2c38edec2db85896b7bbcd18945d2fc64b938a45/pages/api/admin/email/index.ts#L33) as 

templateId: "Z6V0E3HEAHM63SKRA3B05RKVR9AE",

should be refactored as an env variable?

Is it Courrier template or mailjet, same example of the content can help for self-install

**Comment by ntkris** [comment]
Thanks for flagging this. 

I have moved the templateId to an environment variable. Will update the readme for this as well
